export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGNUP = 'SIGNUP'
export const RELOGIN = 'RELOGIN'

export const COMMON_ADD_TAB = 'COMMON_ADD_TAB'
export const COMMON_REMOVE_TAB = 'COMMON_REMOVE_TAB'

export const REDIS_SERVER_ADD_SERVER = 'REDIS_SERVER_ADD_SERVER'
export const REDIS_SERVER_GET_SERVER_LIST = 'REDIS_SERVER_GET_SERVER_LIST'
export const REDIS_SERVER_GET_DATABASE_LIST = 'REDIS_SERVER_GET_DATABASE_LIST'
export const REDIS_SERVER_AUTHENTICATE = 'REDIS_SERVER_AUTHENTICATE'

export const REDIS_DATABASE_GET_KEY_LIST = 'REDIS_DATABASE_GET_KEY_LIST'
export const REDIS_DATABASE_SET_KEY_VALUE = 'REDIS_DATABASE_SET_KEY_VALUE'