export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGNUP = 'SIGNUP'
export const RELOGIN = 'RELOGIN'

export const COMMON_ADD_TAB = 'COMMON_ADD_TAB'
export const COMMON_REMOVE_TAB = 'COMMON_REMOVE_TAB'

export const REDIS_SERVER_ADD_SERVER = 'REDIS_SERVER_ADD_SERVER'
export const REDIS_SERVER_GET_SERVERS = 'REDIS_SERVER_GET_SERVERS'
export const REDIS_SERVER_GET_DATABASES = 'REDIS_SERVER_GET_DATABASES'
export const REDIS_SERVER_AUTHENTICATE = 'REDIS_SERVER_AUTHENTICATE'

export const REDIS_DB_GET_KEYS = 'REDIS_DB_GET_KEYS'